### PR TITLE
Saturate the full dynamic range of the charset

### PR DESCRIPTION
**Pull request by fnordpig**
Today the upper end of the dynamic range of the charset tends to never show up unless a fully saturated pixel appears, which is unlikely given how this works.  This rescales the dynamic range to ensure the full range is possible.

### CODE REVIEW

**Comment by fnordpig** [comment]
Example with Chinese charset with full range:
image
Example without:
image

Block with:
image

Block without:
image

**Comment by RGBCube** [comment]
Looks good, can you run cargo fmt?

**Comment by RGBCube** [comment]
Looks good, can you run cargo fmt?
Also bump the version up one patch

**Comment by fnordpig** [comment]
Blegh, I'm in git hell.

**Comment by RGBCube** [comment]
Thanks!

**Pull request merged**
